### ISSUE TITLE
Exception generated when attempting to backup a lookup file

### ISSUE THREAD

**Issue by alasdairb** [splunk/seckit_sa_geolocation#234]
In Splunk Cloud, seeing an exception generated
SecKit_SA_geolocation_rh_updater.py - Line 124 
except CalledProcessError as e:
NameError: Name 'CalledProcessError' is not defined

**Comment by nkleck** [comment]
I am receiving the same error in Splunk Cloud. has there been any update? Splunkbase states this should be compatible with Splunk Cloud v9.0

```
2023-05-23 06:05:34,188 ERROR pid=3099506 tid=MainThread file=SecKit_SA_geolocation_rh_updater.py:post_update:157 | Exception generated when attempting to backup a lookup file
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SecKit_SA_geolocation/bin/SecKit_SA_geolocation_rh_updater.py", line 122, in post_update
    stderr=subprocess.STDOUT,
  File "/opt/splunk/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/splunk/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['$SPLUNK_HOME/etc/apps/SecKit_SA_geolocation/bin/geoipupdate/linux_amd64/geoipupdate -v -d /opt/splunk/etc/apps/SecKit_SA_geolocation/data/ -f /tmp/GeoIP865qlyc3.conf']' returned non-zero exit status 126.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SecKit_SA_geolocation/bin/SecKit_SA_geolocation_rh_updater.py", line 124, in post_update
    except CalledProcessError as e:
NameError: name 'CalledProcessError' is not defined
```
